/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class AdminJFrame extends javax.swing.JFrame {
    private String tglBerangkatString;
    private String tglLahirString;
    /**
     * Creates new form AdminJFrame
     */
    public AdminJFrame() {
        initComponents();
        CenteredFrame(this);
    }
    
    public void CenteredFrame(javax.swing.JFrame objFrame){
        Dimension objDimension = Toolkit.getDefaultToolkit().getScreenSize();
        int iCoordX = (objDimension.width - objFrame.getWidth()) / 2;
        int iCoordY = (objDimension.height - objFrame.getHeight()) / 2;
        objFrame.setLocation(iCoordX, iCoordY); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane7 = new javax.swing.JTabbedPane();
        jButton4 = new javax.swing.JButton();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTabbedPane10 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbGerbong = new javax.swing.JTable();
        gerbong_edit = new javax.swing.JButton();
        gerbong_simpan = new javax.swing.JButton();
        gerbong_hapus = new javax.swing.JButton();
        gerbong_refresh = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        gerbong_idGerbong = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        gerbong_noGerbong = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        gerbong_kapasitas = new javax.swing.JTextField();
        gerbong_idKereta = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        gerbong_rbTersedia = new javax.swing.JRadioButton();
        gerbong_rbTerisi = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbJadwal = new javax.swing.JTable();
        jadwal_edit = new javax.swing.JButton();
        jadwal_simpan = new javax.swing.JButton();
        jadwal_hapus = new javax.swing.JButton();
        jadwal_refresh = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jadwal_kodeJadwal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jadwal_jamBerangkat = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jadwal_jamTiba = new javax.swing.JTextField();
        jadwal_stasiunAsal = new javax.swing.JComboBox<>();
        jadwal_stasiunTujuan = new javax.swing.JComboBox<>();
        jadwal_tglBerangkat = new com.toedter.calendar.JDateChooser();
        jadwal_idKereta = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbKereta = new javax.swing.JTable();
        kereta_edit = new javax.swing.JButton();
        kereta_simpan = new javax.swing.JButton();
        kereta_hapus = new javax.swing.JButton();
        kereta_refresh = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        kereta_idKereta = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        kereta_namaKereta = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        kereta_kapasitas = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        kereta_rbEksekutif = new javax.swing.JRadioButton();
        kereta_rbBisnis = new javax.swing.JRadioButton();
        kereta_rbEkonomi = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbKursi = new javax.swing.JTable();
        kursi_edit = new javax.swing.JButton();
        kursi_simpan = new javax.swing.JButton();
        kursi_hapus = new javax.swing.JButton();
        kursi_refresh = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        kursi_idKursi = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        kursi_kolomKursi = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        kursi_barisKursi = new javax.swing.JTextField();
        kursi_idGerbong = new javax.swing.JComboBox<>();
        jLabel39 = new javax.swing.JLabel();
        kursi_rbTersedia = new javax.swing.JRadioButton();
        kursi_rbTerisi = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbPetugas = new javax.swing.JTable();
        petugas_edit = new javax.swing.JButton();
        petugas_simpan = new javax.swing.JButton();
        petugas_hapus = new javax.swing.JButton();
        petugas_refresh = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        petugas_idPetugas = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        petugas_nama = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        petugas_noHP = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        petugas_email = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        petugas_rbL = new javax.swing.JRadioButton();
        petugas_rbP = new javax.swing.JRadioButton();
        petugas_tglLahir = new com.toedter.calendar.JDateChooser();
        jScrollPane7 = new javax.swing.JScrollPane();
        petugas_alamat = new javax.swing.JTextArea();
        jLabel38 = new javax.swing.JLabel();
        petugas_password = new javax.swing.JPasswordField();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tbStasiun = new javax.swing.JTable();
        stasiun_edit = new javax.swing.JButton();
        stasiun_simpan = new javax.swing.JButton();
        stasiun_hapus = new javax.swing.JButton();
        stasiun_refresh = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        stasiun_kodeStasiun = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        stasiun_namaStasiun = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        stasiun_daerahOperasi = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        stasiun_rbLokal = new javax.swing.JRadioButton();
        stasiun_rbInterlokal = new javax.swing.JRadioButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        stasiun_alamat = new javax.swing.JTextArea();

        jButton4.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(55, 65, 74));

        jPanel2.setBackground(new java.awt.Color(31, 36, 42));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 65)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(96, 187, 34));
        jLabel1.setText("Tikepi.");

        jLabel2.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(96, 187, 34));
        jLabel2.setText("Kalau bukan sekarang, kapan lagi?");

        jLabel3.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(96, 187, 34));
        jLabel3.setText("Pesan Tiket Kereta Api");

        jLabel4.setFont(new java.awt.Font("Adobe Fan Heiti Std B", 0, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(96, 187, 34));
        jLabel4.setText("Kalau bukan tikepi, apa lagi?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane10.setBackground(new java.awt.Color(31, 36, 42));

        jPanel4.setBackground(new java.awt.Color(31, 36, 42));

        tbGerbong.setBackground(new java.awt.Color(240, 240, 240));
        tbGerbong.setForeground(new java.awt.Color(31, 36, 42));
        tbGerbong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbGerbong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbGerbongMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbGerbong);

        gerbong_edit.setBackground(new java.awt.Color(55, 65, 74));
        gerbong_edit.setForeground(new java.awt.Color(55, 65, 74));
        gerbong_edit.setText("Edit");

        gerbong_simpan.setBackground(new java.awt.Color(55, 65, 74));
        gerbong_simpan.setForeground(new java.awt.Color(55, 65, 74));
        gerbong_simpan.setText("Simpan");
        gerbong_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gerbong_simpanActionPerformed(evt);
            }
        });

        gerbong_hapus.setBackground(new java.awt.Color(55, 65, 74));
        gerbong_hapus.setForeground(new java.awt.Color(55, 65, 74));
        gerbong_hapus.setText("Hapus");

        gerbong_refresh.setBackground(new java.awt.Color(55, 65, 74));
        gerbong_refresh.setForeground(new java.awt.Color(55, 65, 74));
        gerbong_refresh.setText("Refresh");

        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("ID Gerbong");

        jLabel6.setForeground(new java.awt.Color(240, 240, 240));
        jLabel6.setText("ID Kereta");

        jLabel7.setForeground(new java.awt.Color(240, 240, 240));
        jLabel7.setText("No Gerbong");

        jLabel8.setForeground(new java.awt.Color(240, 240, 240));
        jLabel8.setText("Kapasitas");

        jLabel9.setForeground(new java.awt.Color(240, 240, 240));
        jLabel9.setText("Status");

        gerbong_rbTersedia.setBackground(new java.awt.Color(31, 36, 42));
        buttonGroup5.add(gerbong_rbTersedia);
        gerbong_rbTersedia.setForeground(new java.awt.Color(255, 255, 255));
        gerbong_rbTersedia.setText("Tersedia");

        gerbong_rbTerisi.setBackground(new java.awt.Color(31, 36, 42));
        buttonGroup5.add(gerbong_rbTerisi);
        gerbong_rbTerisi.setForeground(new java.awt.Color(255, 255, 255));
        gerbong_rbTerisi.setText("Terisi");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gerbong_kapasitas, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(gerbong_noGerbong)
                    .addComponent(gerbong_idGerbong)
                    .addComponent(gerbong_idKereta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gerbong_rbTersedia)
                            .addComponent(gerbong_rbTerisi))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(gerbong_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gerbong_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(gerbong_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gerbong_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gerbong_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gerbong_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gerbong_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gerbong_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(gerbong_idGerbong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(gerbong_idKereta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(gerbong_noGerbong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(gerbong_kapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(gerbong_rbTersedia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gerbong_rbTerisi)))
                .addContainerGap())
        );

        jTabbedPane10.addTab("Gerbong", jPanel4);

        jPanel5.setBackground(new java.awt.Color(31, 36, 42));

        tbJadwal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbJadwal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbJadwalMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbJadwal);

        jadwal_edit.setBackground(new java.awt.Color(31, 36, 42));
        jadwal_edit.setText("Edit");

        jadwal_simpan.setBackground(new java.awt.Color(31, 36, 42));
        jadwal_simpan.setText("Simpan");

        jadwal_hapus.setBackground(new java.awt.Color(31, 36, 42));
        jadwal_hapus.setText("Hapus");

        jadwal_refresh.setBackground(new java.awt.Color(31, 36, 42));
        jadwal_refresh.setText("Refresh");

        jLabel10.setForeground(new java.awt.Color(240, 240, 240));
        jLabel10.setText("Kode Jadwal");

        jLabel11.setForeground(new java.awt.Color(240, 240, 240));
        jLabel11.setText("ID Kereta");

        jLabel12.setForeground(new java.awt.Color(240, 240, 240));
        jLabel12.setText("Stasiun Asal");

        jLabel13.setForeground(new java.awt.Color(240, 240, 240));
        jLabel13.setText("Stasiun Tujuan");

        jLabel14.setForeground(new java.awt.Color(240, 240, 240));
        jLabel14.setText("Tanggal Berangkat");

        jLabel15.setForeground(new java.awt.Color(240, 240, 240));
        jLabel15.setText("Jam Berangkat");

        jLabel16.setForeground(new java.awt.Color(240, 240, 240));
        jLabel16.setText("Jam Tiba");

        jadwal_tglBerangkat.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jadwal_tglBerangkatPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jadwal_jamTiba, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addComponent(jadwal_jamBerangkat)
                    .addComponent(jadwal_kodeJadwal)
                    .addComponent(jadwal_stasiunAsal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jadwal_stasiunTujuan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jadwal_tglBerangkat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jadwal_idKereta, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jadwal_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jadwal_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jadwal_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jadwal_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jadwal_kodeJadwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jadwal_idKereta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jadwal_stasiunAsal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jadwal_stasiunTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jadwal_tglBerangkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jadwal_jamBerangkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jadwal_jamTiba, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jadwal_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jadwal_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jadwal_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jadwal_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane10.addTab("Jadwal", jPanel5);

        jPanel6.setBackground(new java.awt.Color(31, 36, 42));

        tbKereta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbKereta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKeretaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbKereta);

        kereta_edit.setBackground(new java.awt.Color(31, 36, 42));
        kereta_edit.setText("Edit");

        kereta_simpan.setBackground(new java.awt.Color(31, 36, 42));
        kereta_simpan.setText("Simpan");

        kereta_hapus.setBackground(new java.awt.Color(31, 36, 42));
        kereta_hapus.setText("Hapus");

        kereta_refresh.setBackground(new java.awt.Color(31, 36, 42));
        kereta_refresh.setText("Refresh");

        jLabel17.setForeground(new java.awt.Color(240, 240, 240));
        jLabel17.setText("ID Kereta");

        jLabel18.setForeground(new java.awt.Color(240, 240, 240));
        jLabel18.setText("Nama Kereta");

        jLabel19.setForeground(new java.awt.Color(240, 240, 240));
        jLabel19.setText("Kapasitas");

        jLabel20.setForeground(new java.awt.Color(240, 240, 240));
        jLabel20.setText("Kelas");

        kereta_rbEksekutif.setBackground(new java.awt.Color(31, 36, 42));
        buttonGroup1.add(kereta_rbEksekutif);
        kereta_rbEksekutif.setForeground(new java.awt.Color(240, 240, 240));
        kereta_rbEksekutif.setText("Eksekutif");

        kereta_rbBisnis.setBackground(new java.awt.Color(31, 36, 42));
        buttonGroup1.add(kereta_rbBisnis);
        kereta_rbBisnis.setForeground(new java.awt.Color(240, 240, 240));
        kereta_rbBisnis.setText("Bisnis");

        kereta_rbEkonomi.setBackground(new java.awt.Color(31, 36, 42));
        buttonGroup1.add(kereta_rbEkonomi);
        kereta_rbEkonomi.setForeground(new java.awt.Color(240, 240, 240));
        kereta_rbEkonomi.setText("Ekonomi");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(kereta_kapasitas, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                        .addComponent(kereta_namaKereta, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(kereta_idKereta, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(kereta_rbEksekutif)
                    .addComponent(kereta_rbBisnis)
                    .addComponent(kereta_rbEkonomi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(kereta_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kereta_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(kereta_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kereta_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(kereta_idKereta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(kereta_namaKereta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(kereta_kapasitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(kereta_rbEksekutif))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kereta_rbBisnis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kereta_rbEkonomi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kereta_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kereta_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kereta_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kereta_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane10.addTab("Kereta", jPanel6);

        jPanel7.setBackground(new java.awt.Color(31, 36, 42));

        tbKursi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbKursi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKursiMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbKursi);

        kursi_edit.setBackground(new java.awt.Color(31, 36, 42));
        kursi_edit.setText("Edit");

        kursi_simpan.setBackground(new java.awt.Color(31, 36, 42));
        kursi_simpan.setText("Simpan");

        kursi_hapus.setBackground(new java.awt.Color(31, 36, 42));
        kursi_hapus.setText("Hapus");

        kursi_refresh.setBackground(new java.awt.Color(31, 36, 42));
        kursi_refresh.setText("Refresh");

        jLabel21.setForeground(new java.awt.Color(240, 240, 240));
        jLabel21.setText("ID Kursi");

        jLabel22.setForeground(new java.awt.Color(240, 240, 240));
        jLabel22.setText("ID Gerbong");

        jLabel23.setForeground(new java.awt.Color(240, 240, 240));
        jLabel23.setText("Kolom Kursi");

        jLabel24.setForeground(new java.awt.Color(240, 240, 240));
        jLabel24.setText("Baris Kursi");

        jLabel39.setForeground(new java.awt.Color(240, 240, 240));
        jLabel39.setText("Status");

        kursi_rbTersedia.setBackground(new java.awt.Color(31, 36, 42));
        buttonGroup2.add(kursi_rbTersedia);
        kursi_rbTersedia.setForeground(new java.awt.Color(255, 255, 255));
        kursi_rbTersedia.setText("Tersedia");

        kursi_rbTerisi.setBackground(new java.awt.Color(31, 36, 42));
        buttonGroup2.add(kursi_rbTerisi);
        kursi_rbTerisi.setForeground(new java.awt.Color(255, 255, 255));
        kursi_rbTerisi.setText("Terisi");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kursi_idGerbong, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kursi_rbTersedia)
                                    .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(kursi_kolomKursi, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                                        .addComponent(kursi_idKursi, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(kursi_barisKursi))
                                    .addComponent(kursi_rbTerisi)))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(kursi_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kursi_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(kursi_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kursi_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(kursi_idKursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(kursi_idGerbong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel23)
                            .addComponent(kursi_kolomKursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(kursi_barisKursi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel39)
                            .addComponent(kursi_rbTersedia))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kursi_rbTerisi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kursi_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kursi_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kursi_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kursi_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane10.addTab("Kursi", jPanel7);

        jPanel8.setBackground(new java.awt.Color(31, 36, 42));

        tbPetugas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbPetugas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPetugasMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tbPetugas);

        petugas_edit.setBackground(new java.awt.Color(31, 36, 42));
        petugas_edit.setText("Edit");

        petugas_simpan.setBackground(new java.awt.Color(31, 36, 42));
        petugas_simpan.setText("Simpan");

        petugas_hapus.setBackground(new java.awt.Color(31, 36, 42));
        petugas_hapus.setText("Hapus");

        petugas_refresh.setBackground(new java.awt.Color(31, 36, 42));
        petugas_refresh.setText("Refresh");

        jLabel25.setForeground(new java.awt.Color(240, 240, 240));
        jLabel25.setText("ID Petugas");

        jLabel26.setForeground(new java.awt.Color(240, 240, 240));
        jLabel26.setText("Nama");

        jLabel27.setForeground(new java.awt.Color(240, 240, 240));
        jLabel27.setText("Jenis Kelamin");

        jLabel28.setForeground(new java.awt.Color(240, 240, 240));
        jLabel28.setText("Tanggal Lahir");

        jLabel29.setForeground(new java.awt.Color(240, 240, 240));
        jLabel29.setText("No HP");

        jLabel30.setForeground(new java.awt.Color(240, 240, 240));
        jLabel30.setText("Email");

        jLabel31.setForeground(new java.awt.Color(240, 240, 240));
        jLabel31.setText("Alamat");

        petugas_rbL.setBackground(new java.awt.Color(31, 36, 42));
        buttonGroup4.add(petugas_rbL);
        petugas_rbL.setForeground(new java.awt.Color(240, 240, 240));
        petugas_rbL.setText("Laki-laki");

        petugas_rbP.setBackground(new java.awt.Color(31, 36, 42));
        buttonGroup4.add(petugas_rbP);
        petugas_rbP.setForeground(new java.awt.Color(240, 240, 240));
        petugas_rbP.setText("Perempuan");

        petugas_tglLahir.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                petugas_tglLahirPropertyChange(evt);
            }
        });

        petugas_alamat.setColumns(20);
        petugas_alamat.setRows(5);
        jScrollPane7.setViewportView(petugas_alamat);

        jLabel38.setForeground(new java.awt.Color(240, 240, 240));
        jLabel38.setText("Password");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(petugas_tglLahir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel38))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(petugas_email)
                            .addComponent(petugas_noHP, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(petugas_nama)
                            .addComponent(petugas_idPetugas)
                            .addComponent(jScrollPane7)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(petugas_rbP)
                                    .addComponent(petugas_rbL))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(petugas_password))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(petugas_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(petugas_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(petugas_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(petugas_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(petugas_idPetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(petugas_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(petugas_rbL))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(petugas_rbP)
                        .addGap(9, 9, 9)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(petugas_tglLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(petugas_noHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(petugas_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(petugas_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(petugas_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(petugas_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(petugas_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(petugas_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jTabbedPane10.addTab("Petugas", jPanel8);

        jPanel9.setBackground(new java.awt.Color(31, 36, 42));

        tbStasiun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbStasiun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbStasiunMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(tbStasiun);

        stasiun_edit.setBackground(new java.awt.Color(31, 36, 42));
        stasiun_edit.setText("Edit");

        stasiun_simpan.setBackground(new java.awt.Color(31, 36, 42));
        stasiun_simpan.setText("Simpan");

        stasiun_hapus.setBackground(new java.awt.Color(31, 36, 42));
        stasiun_hapus.setText("Hapus");

        stasiun_refresh.setBackground(new java.awt.Color(31, 36, 42));
        stasiun_refresh.setText("Refresh");

        jLabel33.setForeground(new java.awt.Color(240, 240, 240));
        jLabel33.setText("Kode Stasiun");

        jLabel34.setForeground(new java.awt.Color(240, 240, 240));
        jLabel34.setText("Nama Stasiun");

        jLabel35.setForeground(new java.awt.Color(240, 240, 240));
        jLabel35.setText("Alamat Stasiun");

        jLabel36.setForeground(new java.awt.Color(240, 240, 240));
        jLabel36.setText("Kelas Stasiun");

        jLabel37.setForeground(new java.awt.Color(240, 240, 240));
        jLabel37.setText("Daerah Operasi");

        stasiun_rbLokal.setBackground(new java.awt.Color(31, 36, 42));
        buttonGroup3.add(stasiun_rbLokal);
        stasiun_rbLokal.setForeground(new java.awt.Color(240, 240, 240));
        stasiun_rbLokal.setText("Lokal");

        stasiun_rbInterlokal.setBackground(new java.awt.Color(31, 36, 42));
        buttonGroup3.add(stasiun_rbInterlokal);
        stasiun_rbInterlokal.setForeground(new java.awt.Color(240, 240, 240));
        stasiun_rbInterlokal.setText("Interlokal");

        stasiun_alamat.setColumns(20);
        stasiun_alamat.setRows(5);
        jScrollPane8.setViewportView(stasiun_alamat);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel33)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(stasiun_daerahOperasi, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addComponent(stasiun_namaStasiun)
                    .addComponent(stasiun_kodeStasiun)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stasiun_rbLokal)
                            .addComponent(stasiun_rbInterlokal))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(stasiun_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stasiun_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(stasiun_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(stasiun_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(stasiun_kodeStasiun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel34)
                            .addComponent(stasiun_namaStasiun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel36)
                            .addComponent(stasiun_rbLokal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(stasiun_rbInterlokal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel37)
                            .addComponent(stasiun_daerahOperasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stasiun_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stasiun_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stasiun_refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stasiun_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane10.addTab("Stasiun", jPanel9);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 890, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane10)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gerbong_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gerbong_simpanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gerbong_simpanActionPerformed

    private void jadwal_tglBerangkatPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jadwal_tglBerangkatPropertyChange
        if(jadwal_tglBerangkat.getDate() != null){
            SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
            tglBerangkatString = s.format(jadwal_tglBerangkat.getDate());
        }
    }//GEN-LAST:event_jadwal_tglBerangkatPropertyChange

    private void petugas_tglLahirPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_petugas_tglLahirPropertyChange
        if(petugas_tglLahir.getDate() != null){
            SimpleDateFormat s = new SimpleDateFormat("yyyy-MM-dd");
            tglLahirString = s.format(petugas_tglLahir.getDate());
        }
    }//GEN-LAST:event_petugas_tglLahirPropertyChange

    private void tbGerbongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbGerbongMouseClicked
        int row = tbGerbong.getSelectedRow();
        String idGerbong = tbGerbong.getModel().getValueAt(row, 0).toString();
        String idKereta = tbGerbong.getModel().getValueAt(row, 1).toString();
        String noGerbong = tbGerbong.getModel().getValueAt(row, 2).toString();
        String kapasitas = tbGerbong.getModel().getValueAt(row, 3).toString();
        String status = tbGerbong.getModel().getValueAt(row, 4).toString();
        
        gerbong_idGerbong.setText(idGerbong);
        
        for(int i = 0; i < gerbong_idKereta.getItemCount(); i++){
            if(gerbong_idKereta.getItemAt(i).toString().equals(idKereta)){
                gerbong_idKereta.setSelectedIndex(i);
            }
        }
        
        gerbong_noGerbong.setText(noGerbong);
        gerbong_kapasitas.setText(kapasitas);
        
        if(status.equals("Tersedia")) gerbong_rbTersedia.setSelected(true);
        else gerbong_rbTerisi.setSelected(true);
    }//GEN-LAST:event_tbGerbongMouseClicked

    private void tbJadwalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbJadwalMouseClicked
        int row = tbJadwal.getSelectedRow();
        String kodeJadwal = tbJadwal.getModel().getValueAt(row, 0).toString();
        String idKereta = tbJadwal.getModel().getValueAt(row, 1).toString();
        String stasiunAsal = tbJadwal.getModel().getValueAt(row, 2).toString();
        String stasiunTujuan = tbJadwal.getModel().getValueAt(row, 3).toString();
        String tanggalBerangkat = tbJadwal.getModel().getValueAt(row, 4).toString();
        String jamBerangkat = tbJadwal.getModel().getValueAt(row, 5).toString();
        String jamTiba = tbJadwal.getModel().getValueAt(row, 6).toString();
        
        jadwal_kodeJadwal.setText(kodeJadwal);
        
        for(int i = 0; i < jadwal_idKereta.getItemCount(); i++){
            if(jadwal_idKereta.getItemAt(i).toString().equals(idKereta)){
                jadwal_idKereta.setSelectedIndex(i);
            }
        }
        
        for(int i = 0; i < jadwal_stasiunAsal.getItemCount(); i++){
            if(jadwal_stasiunAsal.getItemAt(i).toString().equals(stasiunAsal)){
                jadwal_stasiunAsal.setSelectedIndex(i);
            }
        }
        
        for(int i = 0; i < jadwal_stasiunTujuan.getItemCount(); i++){
            if(jadwal_stasiunTujuan.getItemAt(i).toString().equals(stasiunTujuan)){
                jadwal_stasiunTujuan.setSelectedIndex(i);
            }
        }
        Date tgl = null;
        DateFormat format = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
        try {
            tgl = format.parse(tanggalBerangkat);
        } catch (ParseException ex) {
            Logger.getLogger(AdminJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        jadwal_tglBerangkat.setDate(tgl);  
        jadwal_jamBerangkat.setText(jamBerangkat);
        jadwal_jamTiba.setText(jamTiba);
    }//GEN-LAST:event_tbJadwalMouseClicked

    private void tbKeretaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKeretaMouseClicked
        int row = tbKereta.getSelectedRow();
        String idKereta = tbKereta.getModel().getValueAt(row, 0).toString();
        String namaKereta = tbKereta.getModel().getValueAt(row, 1).toString();
        String kapasitas = tbKereta.getModel().getValueAt(row, 2).toString();
        String kelasKereta = tbKereta.getModel().getValueAt(row, 3).toString();
        
        kereta_idKereta.setText(idKereta);
        kereta_namaKereta.setText(namaKereta);
        kereta_kapasitas.setText(kapasitas);
        
        if(kelasKereta.equals("Eksekutif")){
            kereta_rbEksekutif.setSelected(true);
        }
        else if (kelasKereta.equals("Bisnis")) { 
            kereta_rbBisnis.setSelected(true);
        } else {
            kereta_rbEkonomi.setSelected(true);
        }
    }//GEN-LAST:event_tbKeretaMouseClicked

    private void tbKursiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKursiMouseClicked
        int row = tbKursi.getSelectedRow();
        String idKursi = tbKursi.getModel().getValueAt(row, 0).toString();
        String idGerbong = tbKursi.getModel().getValueAt(row, 1).toString();
        String kolomKursi = tbKursi.getModel().getValueAt(row, 2).toString();
        String barisKursi = tbKursi.getModel().getValueAt(row, 3).toString();
        String statusKursi = tbKursi.getModel().getValueAt(row, 4).toString();
        
        kursi_idKursi.setText(idKursi);
        for(int i = 0; i < kursi_idGerbong.getItemCount(); i++){
            if(kursi_idGerbong.getItemAt(i).toString().equals(idGerbong)){
                kursi_idGerbong.setSelectedIndex(i);
            }
        }
        
        kursi_kolomKursi.setText(kolomKursi);
        kursi_barisKursi.setText(barisKursi);
        
        if(statusKursi.equals("Tersedia")) kursi_rbTersedia.setSelected(true);
        else kursi_rbTerisi.setSelected(true);
    }//GEN-LAST:event_tbKursiMouseClicked

    private void tbPetugasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPetugasMouseClicked
        int row = tbPetugas.getSelectedRow();
        String idPetugas = tbPetugas.getModel().getValueAt(row, 0).toString();
        String nama = tbPetugas.getModel().getValueAt(row, 1).toString();
        String jenisKelamin = tbPetugas.getModel().getValueAt(row, 2).toString();
        String tanggalLahir = tbPetugas.getModel().getValueAt(row, 3).toString();
        String noHp = tbPetugas.getModel().getValueAt(row, 4).toString();
        String email = tbPetugas.getModel().getValueAt(row, 5).toString();
        String alamat = tbPetugas.getModel().getValueAt(row, 6).toString();
        
        
        Date tgl = null;
        DateFormat format = new SimpleDateFormat("yyyy-MM-dd", Locale.ENGLISH);
        try {
            tgl = format.parse(tanggalLahir);
        } catch (ParseException ex) {
            Logger.getLogger(AdminJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        jadwal_tglBerangkat.setDate(tgl);
        petugas_idPetugas.setText(idPetugas);
        petugas_nama.setText(nama);
        petugas_noHP.setText(noHp);
        petugas_email.setText(email);
        petugas_alamat.setText(alamat);
        
        // radio button
        if(jenisKelamin.equals("L")) petugas_rbL.setSelected(true);
        else petugas_rbP.setSelected(true);
    }//GEN-LAST:event_tbPetugasMouseClicked

    private void tbStasiunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbStasiunMouseClicked
        int row = tbStasiun.getSelectedRow();
        String kodeStasiun = tbStasiun.getModel().getValueAt(row, 0).toString();
        String namaStasiun = tbStasiun.getModel().getValueAt(row, 1).toString();
        String alamatStasiun = tbStasiun.getModel().getValueAt(row, 2).toString();
        String kelasStasiun = tbStasiun.getModel().getValueAt(row, 3).toString();
        String daerahOperasi = tbStasiun.getModel().getValueAt(row, 4).toString();
        
        
        
        stasiun_kodeStasiun.setText(kodeStasiun);
        stasiun_namaStasiun.setText(namaStasiun);
        stasiun_alamat.setText(alamatStasiun);
        stasiun_daerahOperasi.setText(daerahOperasi);
        
        // radio button
        if(kelasStasiun.equals("Lokal")) stasiun_rbLokal.setSelected(true);
        else stasiun_rbInterlokal.setSelected(true);
    }//GEN-LAST:event_tbStasiunMouseClicked

    
    
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JButton gerbong_edit;
    private javax.swing.JButton gerbong_hapus;
    private javax.swing.JTextField gerbong_idGerbong;
    private javax.swing.JComboBox<String> gerbong_idKereta;
    private javax.swing.JTextField gerbong_kapasitas;
    private javax.swing.JTextField gerbong_noGerbong;
    private javax.swing.JRadioButton gerbong_rbTerisi;
    private javax.swing.JRadioButton gerbong_rbTersedia;
    private javax.swing.JButton gerbong_refresh;
    private javax.swing.JButton gerbong_simpan;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane10;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane7;
    private javax.swing.JButton jadwal_edit;
    private javax.swing.JButton jadwal_hapus;
    private javax.swing.JComboBox<String> jadwal_idKereta;
    private javax.swing.JTextField jadwal_jamBerangkat;
    private javax.swing.JTextField jadwal_jamTiba;
    private javax.swing.JTextField jadwal_kodeJadwal;
    private javax.swing.JButton jadwal_refresh;
    private javax.swing.JButton jadwal_simpan;
    private javax.swing.JComboBox<String> jadwal_stasiunAsal;
    private javax.swing.JComboBox<String> jadwal_stasiunTujuan;
    private com.toedter.calendar.JDateChooser jadwal_tglBerangkat;
    private javax.swing.JButton kereta_edit;
    private javax.swing.JButton kereta_hapus;
    private javax.swing.JTextField kereta_idKereta;
    private javax.swing.JTextField kereta_kapasitas;
    private javax.swing.JTextField kereta_namaKereta;
    private javax.swing.JRadioButton kereta_rbBisnis;
    private javax.swing.JRadioButton kereta_rbEkonomi;
    private javax.swing.JRadioButton kereta_rbEksekutif;
    private javax.swing.JButton kereta_refresh;
    private javax.swing.JButton kereta_simpan;
    private javax.swing.JTextField kursi_barisKursi;
    private javax.swing.JButton kursi_edit;
    private javax.swing.JButton kursi_hapus;
    private javax.swing.JComboBox<String> kursi_idGerbong;
    private javax.swing.JTextField kursi_idKursi;
    private javax.swing.JTextField kursi_kolomKursi;
    private javax.swing.JRadioButton kursi_rbTerisi;
    private javax.swing.JRadioButton kursi_rbTersedia;
    private javax.swing.JButton kursi_refresh;
    private javax.swing.JButton kursi_simpan;
    private javax.swing.JTextArea petugas_alamat;
    private javax.swing.JButton petugas_edit;
    private javax.swing.JTextField petugas_email;
    private javax.swing.JButton petugas_hapus;
    private javax.swing.JTextField petugas_idPetugas;
    private javax.swing.JTextField petugas_nama;
    private javax.swing.JTextField petugas_noHP;
    private javax.swing.JPasswordField petugas_password;
    private javax.swing.JRadioButton petugas_rbL;
    private javax.swing.JRadioButton petugas_rbP;
    private javax.swing.JButton petugas_refresh;
    private javax.swing.JButton petugas_simpan;
    private com.toedter.calendar.JDateChooser petugas_tglLahir;
    private javax.swing.JTextArea stasiun_alamat;
    private javax.swing.JTextField stasiun_daerahOperasi;
    private javax.swing.JButton stasiun_edit;
    private javax.swing.JButton stasiun_hapus;
    private javax.swing.JTextField stasiun_kodeStasiun;
    private javax.swing.JTextField stasiun_namaStasiun;
    private javax.swing.JRadioButton stasiun_rbInterlokal;
    private javax.swing.JRadioButton stasiun_rbLokal;
    private javax.swing.JButton stasiun_refresh;
    private javax.swing.JButton stasiun_simpan;
    private javax.swing.JTable tbGerbong;
    private javax.swing.JTable tbJadwal;
    private javax.swing.JTable tbKereta;
    private javax.swing.JTable tbKursi;
    private javax.swing.JTable tbPetugas;
    private javax.swing.JTable tbStasiun;
    // End of variables declaration//GEN-END:variables
    
    public void addActionListener(ActionListener x){
        gerbong_simpan.addActionListener(x);
        gerbong_edit.addActionListener(x);
        gerbong_hapus.addActionListener(x);
        gerbong_refresh.addActionListener(x);
        jadwal_simpan.addActionListener(x);
        jadwal_edit.addActionListener(x);
        jadwal_hapus.addActionListener(x);
        jadwal_refresh.addActionListener(x);
        kereta_simpan.addActionListener(x);
        kereta_edit.addActionListener(x);
        kereta_hapus.addActionListener(x);
        kereta_refresh.addActionListener(x);
        kursi_simpan.addActionListener(x);
        kursi_edit.addActionListener(x);
        kursi_hapus.addActionListener(x);
        kursi_refresh.addActionListener(x);
        petugas_simpan.addActionListener(x);
        petugas_edit.addActionListener(x);
        petugas_hapus.addActionListener(x);
        petugas_refresh.addActionListener(x);
        stasiun_simpan.addActionListener(x);
        stasiun_edit.addActionListener(x);
        stasiun_hapus.addActionListener(x);
        stasiun_refresh.addActionListener(x);
    }
    
    public void addMouseAdapter(MouseAdapter x){
        tbGerbong.addMouseListener(x);
        tbJadwal.addMouseListener(x);
        tbKereta.addMouseListener(x);
        tbKursi.addMouseListener(x);
        tbPetugas.addMouseListener(x);
        tbStasiun.addMouseListener(x);
    }

    public String getTglBerangkatString() {
        return tglBerangkatString;
    }

    public String getTglLahirString() {
        return tglLahirString;
    }

    public JButton getGerbong_edit() {
        return gerbong_edit;
    }

    public JButton getGerbong_hapus() {
        return gerbong_hapus;
    }

    public String getGerbong_idGerbong() {
        return gerbong_idGerbong.getText();
    }
    
    public String getStatusGerbong(){
        if(gerbong_rbTerisi.isSelected()){
            return "Terisi";
        }
        else{
            return "Tersedia";
        }
    }

    public String getGerbong_kapasitas() {
        return gerbong_kapasitas.getText();
    }

    public String getGerbong_noGerbong() {
        return gerbong_noGerbong.getText();
    }

//    public javax.swing.JRadioButton getGerbong_rbPenuh() {
//        return gerbong_rbPenuh;
//    }
//
//    public javax.swing.JRadioButton getGerbong_rbTersedia() {
//        return gerbong_rbTersedia;
//    }
    
    public String getStatusKursi(){
        if(kursi_rbTerisi.isSelected()){
            return "Terisi";
        }
        else{
            return "Tersedia";
        }
    }

    public JButton getGerbong_refresh() {
        return gerbong_refresh;
    }

    public JButton getGerbong_simpan() {
        return gerbong_simpan;
    }

    public JButton getJadwal_edit() {
        return jadwal_edit;
    }

    public JButton getJadwal_hapus() {
        return jadwal_hapus;
    }

    public String getJadwal_idKereta() {
        return jadwal_idKereta.getSelectedItem().toString();
    }

    public String getJadwal_jamBerangkat() {
        return jadwal_jamBerangkat.getText();
    }

    public String getJadwal_jamTiba() {
        return jadwal_jamTiba.getText();
    }

    public String getJadwal_kodeJadwal() {
        return jadwal_kodeJadwal.getText();
    }

    public JButton getJadwal_refresh() {
        return jadwal_refresh;
    }

    public JButton getJadwal_simpan() {
        return jadwal_simpan;
    }

    public String getJadwal_stasiunAsal() {
        return jadwal_stasiunAsal.getSelectedItem().toString();
    }

    public String getJadwal_stasiunTujuan() {
        return jadwal_stasiunTujuan.getSelectedItem().toString();
    }

    public String getJadwal_tglBerangkat() {
        return tglBerangkatString;
    }

    public JButton getKereta_edit() {
        return kereta_edit;
    }

    public JButton getKereta_hapus() {
        return kereta_hapus;
    }

    public String getKereta_idKereta() {
        return kereta_idKereta.getText();
    }

    public String getKereta_kapasitas() {
        return kereta_kapasitas.getText();
    }

    public String getKereta_namaKereta() {
        return kereta_namaKereta.getText();
    }

//    public javax.swing.JRadioButton getKereta_rbBisnis() {
//        return kereta_rbBisnis;
//    }
//
//    public javax.swing.JRadioButton getKereta_rbEkonomi() {
//        return kereta_rbEkonomi;
//    }
//
//    public javax.swing.JRadioButton getKereta_rbEksekutif() {
//        return kereta_rbEksekutif;
//    }
    
    public String getKelasKereta(){
        if(kereta_rbBisnis.isSelected()){
            return "Bisnis";
        }
        else if(kereta_rbEkonomi.isSelected()){
            return "Ekonomi";
        }
        else{
            return "Eksekutif";
        }
    }

    public JButton getKereta_refresh() {
        return kereta_refresh;
    }

    public JButton getKereta_simpan() {
        return kereta_simpan;
    }

    public String getKursi_barisKursi() {
        return kursi_barisKursi.getText();
    }

    public JButton getKursi_edit() {
        return kursi_edit;
    }

    public JButton getKursi_hapus() {
        return kursi_hapus;
    }

    public String getKursi_idGerbong() {
        return kursi_idGerbong.getSelectedItem().toString();
    }

    public String getKursi_idKursi() {
        return kursi_idKursi.getText();
    }

    public String getKursi_kolomKursi() {
        return kursi_kolomKursi.getText();
    }

    public JButton getKursi_refresh() {
        return kursi_refresh;
    }

    public JButton getKursi_simpan() {
        return kursi_simpan;
    }

    public String getPetugas_alamat() {
        return petugas_alamat.getText();
    }

    public JButton getPetugas_edit() {
        return petugas_edit;
    }

    public String getPetugas_email() {
        return petugas_email.getText();
    }

    public JButton getPetugas_hapus() {
        return petugas_hapus;
    }

    public String getPetugas_idPetugas() {
        return petugas_idPetugas.getText();
    }

    public String getPetugas_nama() {
        return petugas_nama.getText();
    }

    public String getPetugas_noHP() {
        return petugas_noHP.getText();
    }

//    public javax.swing.JRadioButton getPetugas_rbL() {
//        return petugas_rbL;
//    }
//
//    public javax.swing.JRadioButton getPetugas_rbP() {
//        return petugas_rbP;
//    }
    
    public String getJKPetugas(){
        if(petugas_rbL.isSelected()){
            return "L";
        }
        else{
            return "P";
        }
    }

    public JButton getPetugas_refresh() {
        return petugas_refresh;
    }

    public JButton getPetugas_simpan() {
        return petugas_simpan;
    }

    public String getPetugas_tglLahir() {
        return tglLahirString;
    }
    
    public String getPetugas_password(){
        return petugas_password.getText();
    }

    public String getStasiun_alamat() {
        return stasiun_alamat.getText();
    }

    public String getStasiun_daerahOperasi() {
        return stasiun_daerahOperasi.getText();
    }

    public JButton getStasiun_edit() {
        return stasiun_edit;
    }

    public JButton getStasiun_hapus() {
        return stasiun_hapus;
    }

    public String getStasiun_kodeStasiun() {
        return stasiun_kodeStasiun.getText();
    }

    public String getStasiun_namaStasiun() {
        return stasiun_namaStasiun.getText();
    }

//    public javax.swing.JRadioButton getStasiun_rbLokal() {
//        return stasiun_rbLokal;
//    }
//    
//    public javax.swing.JRadioButton getStasiun_rbInterlokal() {
//        return stasiun_rbInterlokal;
//    }
    
    public String getKelasStasiun(){
        if(stasiun_rbLokal.isSelected()){
            return "Lokal";
        }
        else{
            return "Interlokal";
        }
    }

    public JButton getStasiun_refresh() {
        return stasiun_refresh;
    }

    public JButton getStasiun_simpan() {
        return stasiun_simpan;
    }
    
    

    public void setTbGerbong(DefaultTableModel tbGerbong) {
        this.tbGerbong.setModel(tbGerbong);
    }

    public void setTbJadwal(DefaultTableModel tbJadwal) {
        this.tbJadwal.setModel(tbJadwal);
    }

    public void setTbKereta(DefaultTableModel tbKereta) {
        this.tbKereta.setModel(tbKereta);
    }

    public void setTbKursi(DefaultTableModel tbKursi) {
        this.tbKursi.setModel(tbKursi);
    }

    public void setTbPetugas(DefaultTableModel tbPetugas) {
        this.tbPetugas.setModel(tbPetugas);
    }

    public void setTbStasiun(DefaultTableModel tbStasiun) {
        this.tbStasiun.setModel(tbStasiun);
    }

    public void setJadwal_idKereta(String jadwal_idKereta) {
        this.jadwal_idKereta.addItem(jadwal_idKereta);
    }

    public void setJadwal_stasiunAsal(String jadwal_stasiunAsal) {
        this.jadwal_stasiunAsal.addItem(jadwal_stasiunAsal);
    }

    public void setJadwal_stasiunTujuan(String jadwal_stasiunTujuan) {
        this.jadwal_stasiunTujuan.addItem(jadwal_stasiunTujuan);
    }

    public void setKursi_idGerbong(String kursi_idGerbong) {
        this.kursi_idGerbong.addItem(kursi_idGerbong);
    }

    public void setGerbong_idKereta(String gerbong_idKereta) {
        this.gerbong_idKereta.addItem(gerbong_idKereta);
    }
    
    public String getGerbong_idKereta(){
        return gerbong_idKereta.getSelectedItem().toString();
    }
    
    
    
    
}
